openapi: 3.0.3
info:
  title: Free Diet - Meals API
  description: Meal CRUD operations
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Development server

tags:
  - name: Meals
    description: Meal management operations

paths:
  /meals:
    post:
      tags:
        - Meals
      summary: Create meal
      description: |
        Saves meal to user profile with food items. Triggers DailyLog recalculation.
        (Spec §FR-014, §US3)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - category
                - foodItems
              properties:
                photoId:
                  type: string
                  format: uuid
                  description: Optional reference to photo (§FR-005b)
                  nullable: true
                category:
                  type: string
                  enum: [BREAKFAST, LUNCH, DINNER, SNACK]
                  description: Meal category (§FR-012, §FR-013)
                date:
                  type: string
                  format: date-time
                  description: Meal date/time. Defaults to now if not provided
                foodItems:
                  type: array
                  minItems: 1
                  description: Must have at least 1 item (§Edge Cases)
                  items:
                    $ref: '#/components/schemas/FoodItemInput'
      responses:
        '201':
          description: Meal created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                noItems:
                  value:
                    error: "Meal must contain at least one food item"
        '401':
          $ref: '#/components/responses/Unauthorized'

    get:
      tags:
        - Meals
      summary: List user meals
      description: |
        Returns user's meals with optional date filtering. Used for meal history.
      security:
        - bearerAuth: []
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date
          description: Filter meals from this date (inclusive)
        - name: endDate
          in: query
          schema:
            type: string
            format: date
          description: Filter meals until this date (inclusive)
        - name: category
          in: query
          schema:
            type: string
            enum: [BREAKFAST, LUNCH, DINNER, SNACK]
          description: Filter by meal category
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Meals retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  meals:
                    type: array
                    items:
                      $ref: '#/components/schemas/Meal'
                  total:
                    type: integer
                    description: Total count of meals matching filters
                  limit:
                    type: integer
                  offset:
                    type: integer

  /meals/{mealId}:
    get:
      tags:
        - Meals
      summary: Get meal by ID
      description: Returns single meal with all food items
      security:
        - bearerAuth: []
      parameters:
        - name: mealId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Meal retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      tags:
        - Meals
      summary: Update meal
      description: |
        Updates meal. Can modify category, date, or food items. Triggers DailyLog recalculation.
        (Spec §FR-010, §FR-011 - edit weights and recalculate)
      security:
        - bearerAuth: []
      parameters:
        - name: mealId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  enum: [BREAKFAST, LUNCH, DINNER, SNACK]
                date:
                  type: string
                  format: date-time
                foodItems:
                  type: array
                  description: Replaces all food items if provided
                  items:
                    $ref: '#/components/schemas/FoodItemInput'
      responses:
        '200':
          description: Meal updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - Meals
      summary: Delete meal
      description: Deletes meal and all associated food items. Triggers DailyLog recalculation.
      security:
        - bearerAuth: []
      parameters:
        - name: mealId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Meal deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'

  /meals/suggest-category:
    get:
      tags:
        - Meals
      summary: Suggest meal category by time
      description: |
        Returns suggested meal category based on current or provided time.
        (Spec §FR-012 - time-based suggestions)
      security:
        - bearerAuth: []
      parameters:
        - name: time
          in: query
          schema:
            type: string
            format: time
          description: Time to check (HH:mm format). Defaults to current time.
          example: "14:30"
      responses:
        '200':
          description: Category suggestion
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestedCategory:
                    type: string
                    enum: [BREAKFAST, LUNCH, DINNER, SNACK]
                    description: |
                      Suggestion logic (§FR-012):
                      - 6:00-11:00 → BREAKFAST
                      - 11:00-16:00 → LUNCH
                      - 16:00-21:00 → DINNER
                      - Other times → SNACK
                  time:
                    type: string
                    format: time
                    description: Time used for suggestion
                  reasoning:
                    type: string
                    description: Human-readable explanation
                    example: "It's 14:30, which is lunch time (11:00-16:00)"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FoodItemInput:
      type: object
      required:
        - name
        - weight
        - caloriesPer100g
        - proteinPer100g
        - fatsPer100g
        - carbsPer100g
      properties:
        name:
          type: string
          description: Food product name
          example: "Куриная грудка"
        weight:
          type: number
          format: float
          minimum: 0.1
          description: Weight in grams (§FR-010)
          example: 200.0
        caloriesPer100g:
          type: number
          format: float
          minimum: 0
          description: Calories per 100g
          example: 165.0
        proteinPer100g:
          type: number
          format: float
          minimum: 0
          example: 31.0
        fatsPer100g:
          type: number
          format: float
          minimum: 0
          example: 3.6
        carbsPer100g:
          type: number
          format: float
          minimum: 0
          example: 0.0
        addedManually:
          type: boolean
          default: false
          description: True if user added, false if API recognized (§FR-023)

    Meal:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        photoId:
          type: string
          format: uuid
          nullable: true
        date:
          type: string
          format: date-time
        category:
          type: string
          enum: [BREAKFAST, LUNCH, DINNER, SNACK]
        totalCalories:
          type: number
          format: float
          description: Calculated from food items
        totalProtein:
          type: number
          format: float
        totalFats:
          type: number
          format: float
        totalCarbs:
          type: number
          format: float
        createdAt:
          type: string
          format: date-time
        foodItems:
          type: array
          items:
            $ref: '#/components/schemas/FoodItem'

    FoodItem:
      allOf:
        - $ref: '#/components/schemas/FoodItemInput'
        - type: object
          properties:
            id:
              type: string
              format: uuid
            mealId:
              type: string
              format: uuid

    Error:
      type: object
      properties:
        error:
          type: string

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Meal not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Meal not found"

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
